site_name: Edu_Platform

theme:
  name: material

nav:
  - Home: index.md
  - Roadmap: roadmap.md
  - Rules: rules.md
  - Courses:
      - Python for Ops: 
          - Module 01: courses/python-for-ops/module-01/lesson.md
      - Grade 7 Physics: 